export const tagCategories = [
  {
    name: "Gatunki",
    tags: [
      { polish: "Akcja", english: "Action" },
      { polish: "Przygoda", english: "Adventure" },
      { polish: "Komedia", english: "Comedy" },
      { polish: "Dramat", english: "Drama" },
      { polish: "Ecchi", english: "Ecchi" },
      { polish: "Fantastyka", english: "Fantasy" },
      { polish: "Horror", english: "Horror" },
      { polish: "Magiczna Dziewczyna", english: "Mahou Shoujo" },
      { polish: "Mecha", english: "Mecha" },
      { polish: "Muzyka", english: "Music" },
      { polish: "Tajemnica", english: "Mystery" },
      { polish: "Psychologiczny", english: "Psychological" },
      { polish: "Romans", english: "Romance" },
      { polish: "Science Fiction", english: "Sci-Fi" },
      { polish: "Życie Codzienne", english: "Slice of Life" },
      { polish: "Sport", english: "Sports" },
      { polish: "Nadprzyrodzone", english: "Supernatural" },
      { polish: "Thriller", english: "Thriller" },
      { polish: "Hentai", english: "Hentai" },
    ],
  },
  {
    name: "Obsada / Główna Obsada",
    tags: [
      { polish: "Antybohater", english: "Anti-Hero" },
      { polish: "Starszy Protagonista", english: "Elderly Protagonist" },
      { polish: "Zbiorowa Obsada", english: "Ensemble Cast" },
      { polish: "Rozdzielona Rodzina", english: "Estranged Family" },
      { polish: "Kobieta Protagonista", english: "Female Protagonist" },
      { polish: "Mężczyzna Protagonista", english: "Male Protagonist" },
      { polish: "Głównie Dorosła Obsada", english: "Primarily Adult Cast" },
      { polish: "Głównie Zwierzęca Obsada", english: "Primarily Animal Cast" },
      { polish: "Głównie Dziecięca Obsada", english: "Primarily Child Cast" },
      { polish: "Głównie Żeńska Obsada", english: "Primarily Female Cast" },
      { polish: "Głównie Męska Obsada", english: "Primarily Male Cast" },
      { polish: "Głównie Nastolatkowa Obsada", english: "Primarily Teen Cast" },
    ],
  },
  {
    name: "Obsada / Cechy",
    tags: [
      { polish: "Regresja Wiekowa", english: "Age Regression" },
      { polish: "Bezpłciowość", english: "Agender" },
      { polish: "Obcy", english: "Aliens" },
      { polish: "Amnezja", english: "Amnesia" },
      { polish: "Anioły", english: "Angels" },
      { polish: "Antropomorfizm", english: "Anthropomorphism" },
      { polish: "Aromantyczność", english: "Aromantic" },
      { polish: "Aranżowane Małżeństwo", english: "Arranged Marriage" },
      { polish: "Sztuczna Inteligencja", english: "Artificial Intelligence" },
      { polish: "Bezpłciowość", english: "Asexual" },
      { polish: "Lokaj", english: "Butler" },
      { polish: "Centaur", english: "Centaur" },
      { polish: "Chimera", english: "Chimera" },
      { polish: "Chuunibyou", english: "Chuunibyou" },
      { polish: "Klon", english: "Clone" },
      { polish: "Cosplay", english: "Cosplay" },
      { polish: "Kowboje", english: "Cowboys" },
      { polish: "Crossdressing", english: "Crossdressing" },
      { polish: "Cyborg", english: "Cyborg" },
      { polish: "Chuligani", english: "Delinquents" },
      { polish: "Demony", english: "Demons" },
      { polish: "Detektyw", english: "Detective" },
      { polish: "Dinozaury", english: "Dinosaurs" },
      { polish: "Niepełnosprawność", english: "Disability" },
      { polish: "Rozszczepiona Tożsamość", english: "Dissociative Identities" },
      { polish: "Smoki", english: "Dragons" },
      { polish: "Dullahan", english: "Dullahan" },
      { polish: "Elf", english: "Elf" },
      { polish: "Wróżka", english: "Fairy" },
      { polish: "Femboy", english: "Femboy" },
      { polish: "Duch", english: "Ghost" },
      { polish: "Goblin", english: "Goblin" },
      { polish: "Bogowie", english: "Gods" },
      { polish: "Gyaru", english: "Gyaru" },
      { polish: "Hikikomori", english: "Hikikomori" },
      { polish: "Bezdomny", english: "Homeless" },
      { polish: "Idol", english: "Idol" },
      { polish: "Kemonomimi", english: "Kemonomimi" },
      { polish: "Kuudere", english: "Kuudere" },
      { polish: "Pokojówki", english: "Maids" },
      { polish: "Syrena", english: "Mermaid" },
      { polish: "Chłopiec-Potwór", english: "Monster Boy" },
      { polish: "Dziewczyna-Potwór", english: "Monster Girl" },
      { polish: "Nekomimi", english: "Nekomimi" },
      { polish: "Ninja", english: "Ninja" },
      { polish: "Nagość", english: "Nudity" },
      { polish: "Zakonnica", english: "Nun" },
      { polish: "Pracownica Biurowa", english: "Office Lady" },
      { polish: "Oiran", english: "Oiran" },
      { polish: "Ojou-sama", english: "Ojou-sama" },
      { polish: "Sierota", english: "Orphan" },
      { polish: "Piraci", english: "Pirates" },
      { polish: "Roboty", english: "Robots" },
      { polish: "Samuraj", english: "Samuraj" },
      { polish: "Kapłanka", english: "Shrine Maiden" },
      { polish: "Szkielet", english: "Skeleton" },
      { polish: "Sukkub", english: "Succubus" },
      { polish: "Opalona Skóra", english: "Tanned Skin" },
      { polish: "Nauczyciel", english: "Teacher" },
      { polish: "Chłopczyca", english: "Tomboy" },
      { polish: "Transpłciowość", english: "Transgender" },
      { polish: "Tsundere", english: "Tsundere" },
      { polish: "Bliźnięta", english: "Twins" },
      { polish: "Wampir", english: "Vampire" },
      { polish: "Weterynarz", english: "Veterinarian" },
      { polish: "Wikingowie", english: "Vikings" },
      { polish: "Zła Królowa", english: "Villainess" },
      { polish: "VTuber", english: "VTuber" },
      { polish: "Wilkołak", english: "Werewolf" },
      { polish: "Wiedźma", english: "Witch" },
      { polish: "Yandere", english: "Yandere" },
      { polish: "Zombie", english: "Zombie" },
    ],
  },
  {
    name: "Demografia",
    tags: [
      { polish: "Josei", english: "Josei" },
      { polish: "Dzieci", english: "Kids" },
      { polish: "Seinen", english: "Seinen" },
      { polish: "Shoujo", english: "Shoujo" },
      { polish: "Shounen", english: "Shounen" },
    ],
  },
  {
    name: "Sceneria",
    tags: [{ polish: "Matriarchat", english: "Matriarchy" }],
  },
  {
    name: "Sceneria / Miejsce",
    tags: [
      { polish: "Bar", english: "Bar" },
      { polish: "Szkoła z Internatem", english: "Boarding School" },
      { polish: "Biwakowanie", english: "Camping" },
      { polish: "Cyrk", english: "Circus" },
      { polish: "Nadmorska", english: "Coastal" },
      { polish: "Studia", english: "College" },
      { polish: "Pustynia", english: "Desert" },
      { polish: "Loch", english: "Dungeon" },
      { polish: "Zagraniczna", english: "Foreign" },
      { polish: "Gospoda", english: "Inn" },
      { polish: "Konbini", english: "Konbini" },
      { polish: "Katastrofa Naturalna", english: "Natural Disaster" },
      { polish: "Biuro", english: "Office" },
      { polish: "Na Zewnątrz", english: "Outdoor" },
      { polish: "Więzienie", english: "Prison" },
      { polish: "Restauracja", english: "Restaurant" },
      { polish: "Wiejska", english: "Rural" },
      { polish: "Szkoła", english: "School" },
      { polish: "Szkolny Klub", english: "School Club" },
      { polish: "Śnieżny Krajobraz", english: "Snowscape" },
      { polish: "Miejska", english: "Urban" },
      { polish: "Praca", english: "Work" },
    ],
  },
  {
    name: "Sceneria / Czas",
    tags: [
      { polish: "Porządek Achroniczny", english: "Achronological Order" },
      { polish: "Anachronizm", english: "Anachronism" },
      { polish: "Starożytne Chiny", english: "Ancient China" },
      { polish: "Dystopia", english: "Dystopian" },
      { polish: "Historyczna", english: "Historical" },
      { polish: "Skok Czasowy", english: "Time Skip" },
    ],
  },
  {
    name: "Sceneria / Wszechświat",
    tags: [
      { polish: "Życie Po Śmierci", english: "Afterlife" },
      { polish: "Alternatywny Wszechświat", english: "Alternate Universe" },
      { polish: "Rozszerzona Rzeczywistość", english: "Augmented Reality" },
      { polish: "Omegaverse", english: "Omegaverse" },
      { polish: "Postapokaliptyczna", english: "Post-Apocalyptic" },
      { polish: "Kosmos", english: "Space" },
      { polish: "Miejska Fantastyka", english: "Urban Fantasy" },
      { polish: "Wirtualny Świat", english: "Virtual World" },
    ],
  },
  {
    name: "Tematy / Akcja",
    tags: [
      { polish: "Łucznictwo", english: "Archery" },
      { polish: "Bitwa Royale", english: "Battle Royale" },
      { polish: "Szpiegostwo", english: "Espionage" },
      { polish: "Zbieg", english: "Fugitive" },
      { polish: "Broń Palna", english: "Guns" },
      { polish: "Sztuki Walki", english: "Martial Arts" },
      { polish: "Walka Włócznią", english: "Spearplay" },
      { polish: "Walka Mieczem", english: "Swordplay" },
    ],
  },
  {
    name: "Tematy / Sztuka",
    tags: [
      { polish: "Aktorstwo", english: "Acting" },
      { polish: "Kaligrafia", english: "Calligraphy" },
      { polish: "Klasyczna Literatura", english: "Classic Literature" },
      { polish: "Rysowanie", english: "Drawing" },
      { polish: "Moda", english: "Fashion" },
      { polish: "Jedzenie", english: "Food" },
      { polish: "Makijaż", english: "Makeup" },
      { polish: "Fotografia", english: "Photography" },
      { polish: "Rakugo", english: "Rakugo" },
      { polish: "Pisanie", english: "Writing" },
    ],
  },
  {
    name: "Tematy / Sztuka-Muzyka",
    tags: [
      { polish: "Zespół", english: "Band" },
      { polish: "Muzyka Klasyczna", english: "Classical Music" },
      { polish: "Taniec", english: "Dancing" },
      { polish: "Hip-hop", english: "Hip-hop Music" },
      { polish: "Jazz", english: "Jazz Music" },
      { polish: "Metal", english: "Metal Music" },
      { polish: "Teatr Muzyczny", english: "Musical Theater" },
      { polish: "Rock", english: "Rock Music" },
    ],
  },
  {
    name: "Tematy / Komedia",
    tags: [
      { polish: "Parodia", english: "Parody" },
      { polish: "Satyra", english: "Satire" },
      { polish: "Slapstick", english: "Slapstick" },
      { polish: "Surrealistyczna Komedia", english: "Surreal Comedy" },
    ],
  },
  {
    name: "Tematy / Dramat",
    tags: [
      { polish: "Przemoc Szkolna", english: "Bullying" },
      { polish: "Walka Klas", english: "Class Struggle" },
      { polish: "Wejście w Dorosłość", english: "Coming of Age" },
      { polish: "Spisek", english: "Conspiracy" },
      { polish: "Eko-Horror", english: "Eco-Horror" },
      { polish: "Fałszywy Związek", english: "Fake Relationship" },
      { polish: "Zarządzanie Królestwem", english: "Kingdom Management" },
      { polish: "Rehabilitacja", english: "Rehabilitation" },
      { polish: "Zemsta", english: "Revenge" },
      { polish: "Samobójstwo", english: "Suicide" },
      { polish: "Tragedia", english: "Tragedy" },
    ],
  },
  {
    name: "Tematy / Fantasy",
    tags: [
      { polish: "Alchemia", english: "Alchemy" },
      { polish: "Zamiana Ciał", english: "Body Swapping" },
      { polish: "Kultywacja", english: "Cultivation" },
      { polish: "Klątwy", english: "Curses" },
      { polish: "Egzorcyzmy", english: "Exorcism" },
      { polish: "Baśń", english: "Fairy Tale" },
      { polish: "Henshin", english: "Henshin" },
      { polish: "Isekai", english: "Isekai" },
      { polish: "Kaiju", english: "Kaiju" },
      { polish: "Magia", english: "Magic" },
      { polish: "Mitologia", english: "Mythology" },
      { polish: "Nekromancja", english: "Necromancy" },
      { polish: "Zmiennokształtność", english: "Shapeshifting" },
      { polish: "Steampunk", english: "Steampunk" },
      { polish: "Supermoce", english: "Super Power" },
      { polish: "Superbohaterowie", english: "Superhero" },
      { polish: "Wuxia", english: "Wuxia" },
      { polish: "Youkai", english: "Youkai" },
    ],
  },
  {
    name: "Tematy / Gry",
    tags: [
      { polish: "Gry Planszowe", english: "Board Game" },
      { polish: "E-Sport", english: "E-Sports" },
      { polish: "Gry Wideo", english: "Video Games" },
    ],
  },
  {
    name: "Tematy / Gry-Karciane & Planszowe",
    tags: [
      { polish: "Walka Kartami", english: "Card Battle" },
      { polish: "Go", english: "Go" },
      { polish: "Karuta", english: "Karuta" },
      { polish: "Mahjong", english: "Mahjong" },
      { polish: "Poker", english: "Poker" },
      { polish: "Shogi", english: "Shogi" },
    ],
  },
  {
    name: "Tematy / Gry-Sportowe",
    tags: [
      { polish: "Akrobatyka", english: "Acrobatics" },
      { polish: "Airsoft", english: "Airsoft" },
      { polish: "Futbol Amerykański", english: "American Football" },
      { polish: "Lekkoatletyka", english: "Athletics" },
      { polish: "Badminton", english: "Badminton" },
      { polish: "Baseball", english: "Baseball" },
      { polish: "Koszykówka", english: "Basketball" },
      { polish: "Kręgle", english: "Bowling" },
      { polish: "Boks", english: "Boxing" },
      { polish: "Cheerleading", english: "Cheerleading" },
      { polish: "Kolarstwo", english: "Cycling" },
      { polish: "Szermierka", english: "Fencing" },
      { polish: "Wędkarstwo", english: "Fishing" },
      { polish: "Fitness", english: "Fitness" },
      { polish: "Piłka Nożna", english: "Football" },
      { polish: "Golf", english: "Golf" },
      { polish: "Piłka Ręczna", english: "Handball" },
      { polish: "Łyżwiarstwo", english: "Ice Skating" },
      { polish: "Judo", english: "Judo" },
      { polish: "Lacrosse", english: "Lacrosse" },
      { polish: "Parkour", english: "Parkour" },
      { polish: "Rugby", english: "Rugby" },
      { polish: "Nurkowanie", english: "Scuba Diving" },
      { polish: "Deskorolka", english: "Skateboarding" },
      { polish: "Sumo", english: "Sumo" },
      { polish: "Surfing", english: "Surfing" },
      { polish: "Pływanie", english: "Swimming" },
      { polish: "Tenis Stołowy", english: "Table Tennis" },
      { polish: "Tenis", english: "Tennis" },
      { polish: "Siatkówka", english: "Volleyball" },
      { polish: "Wrestling", english: "Wrestling" },
    ],
  },
  {
    name: "Tematy / Inne",
    tags: [
      { polish: "Adopcja", english: "Adoption" },
      { polish: "Zwierzęta", english: "Animals" },
      { polish: "Astronomia", english: "Astronomy" },
      { polish: "Autobiograficzne", english: "Autobiographical" },
      { polish: "Biograficzne", english: "Biographical" },
      { polish: "Horror Ciała", english: "Body Horror" },
      { polish: "Kanibalizm", english: "Cannibalism" },
      { polish: "Chibi", english: "Chibi" },
      { polish: "Kosmiczny Horror", english: "Cosmic Horror" },
      { polish: "Kryminał", english: "Crime" },
      { polish: "Crossover", english: "Crossover" },
      { polish: "Gra Śmierci", english: "Death Game" },
      { polish: "Denpa", english: "Denpa" },
      { polish: "Narkotyki", english: "Drugs" },
      { polish: "Ekonomia", english: "Economics" },
      { polish: "Edukacyjne", english: "Educational" },
      { polish: "Ekologia", english: "Environmental" },
      { polish: "Ero Guro", english: "Ero Guro" },
      { polish: "Tworzenie Filmów", english: "Filmmaking" },
      { polish: "Znaleziona Rodzina", english: "Found Family" },
      { polish: "Hazard", english: "Gambling" },
      { polish: "Zmiana Płci", english: "Gender Bending" },
      { polish: "Gore", english: "Gore" },
      { polish: "Bariera Językowa", english: "Language Barrier" },
      { polish: "Motyw LGBTQ+", english: "LGBTQ+ Themes" },
      { polish: "Zaginiona Cywilizacja", english: "Lost Civilization" },
      { polish: "Małżeństwo", english: "Marriage" },
      { polish: "Medycyna", english: "Medicine" },
      { polish: "Manipulacja Pamięcią", english: "Memory Manipulation" },
      { polish: "Meta", english: "Meta" },
      { polish: "Wspinaczka Górska", english: "Mountaineering" },
      { polish: "Noir", english: "Noir" },
      { polish: "Kultura Otaku", english: "Otaku Culture" },
      { polish: "Pandemia", english: "Pandemic" },
      { polish: "Filozofia", english: "Philosophy" },
      { polish: "Polityka", english: "Politics" },
      { polish: "Walka przez Pełnomocnika", english: "Proxy Battle" },
      { polish: "Psychoseksualne", english: "Psychosexual" },
      { polish: "Reinkarnacja", english: "Reincarnation" },
      { polish: "Religia", english: "Religion" },
      { polish: "Sprawy Królewskie", english: "Royal Affairs" },
      { polish: "Niewolnictwo", english: "Slavery" },
      { polish: "Tworzenie Oprogramowania", english: "Software Development" },
      { polish: "Przetrwanie", english: "Survival" },
      { polish: "Terroryzm", english: "Terrorism" },
      { polish: "Tortury", english: "Torture" },
      { polish: "Podróże", english: "Travel" },
      { polish: "Syntezator Wokalny", english: "Vocal Synth" },
      { polish: "Wojna", english: "War" },
    ],
  },
  {
    name: "Tematy / Inne-Organizacje",
    tags: [
      { polish: "Zabójcy", english: "Assassins" },
      { polish: "Organizacja Przestępcza", english: "Criminal Organization" },
      { polish: "Kult", english: "Cult" },
      { polish: "Strażacy", english: "Firefighters" },
      { polish: "Gangi", english: "Gangs" },
      { polish: "Mafia", english: "Mafia" },
      { polish: "Wojsko", english: "Military" },
      { polish: "Policja", english: "Police" },
      { polish: "Triady", english: "Triads" },
      { polish: "Yakuza", english: "Yakuza" },
    ],
  },
  {
    name: "Tematy / Inne-Pojazdy",
    tags: [
      { polish: "Lotnictwo", english: "Aviation" },
      { polish: "Samochody", english: "Cars" },
      { polish: "Motorowery", english: "Mopeds" },
      { polish: "Motocykle", english: "Motorcycles" },
      { polish: "Statki", english: "Ships" },
      { polish: "Czołgi", english: "Tanks" },
      { polish: "Pociągi", english: "Trains" },
    ],
  },
  {
    name: "Tematy / Romans",
    tags: [
      { polish: "Różnica Wiekowa", english: "Age Gap" },
      { polish: "Biseksualność", english: "Bisexual" },
      { polish: "Boys' Love", english: "Boys' Love" },
      { polish: "Harem Żeński", english: "Female Harem" },
      { polish: "Heteroseksualny", english: "Heterosexual" },
      { polish: "Trójkąt Miłosny", english: "Love Triangle" },
      { polish: "Harem Męski", english: "Male Harem" },
      { polish: "Swatka", english: "Matchmaking" },
      { polish: "Harem Mieszany", english: "Mixed Gender Harem" },
      { polish: "Poliamoria", english: "Polyamorous" },
      { polish: "Miłość Nastolatków", english: "Teens' Love" },
      { polish: "Niespełniona Miłość", english: "Unrequited Love" },
      { polish: "Yuri", english: "Yuri" },
    ],
  },
  {
    name: "Tematy / Science Fiction",
    tags: [
      { polish: "Cyberpunk", english: "Cyberpunk" },
      { polish: "Opera Kosmiczna", english: "Space Opera" },
      { polish: "Pętla Czasowa", english: "Time Loop" },
      { polish: "Manipulacja Czasem", english: "Time Manipulation" },
      { polish: "Tokusatsu", english: "Tokusatsu" },
    ],
  },
  {
    name: "Tematy / Science Fiction-Mecha",
    tags: [
      { polish: "Real Robot", english: "Real Robot" },
      { polish: "Super Robot", english: "Super Robot" },
    ],
  },
  {
    name: "Tematy / Slice of Life",
    tags: [
      { polish: "Rolnictwo", english: "Agriculture" },
      { polish: "Słodcy Chłopcy Robią Słodkie Rzeczy", english: "Cute Boys Doing Cute Things" },
      { polish: "Słodkie Dziewczyny Robią Słodkie Rzeczy", english: "Cute Girls Doing Cute Things" },
      { polish: "Życie Rodzinne", english: "Family Life" },
      { polish: "Hodowla Roślin", english: "Horticulture" },
      { polish: "Iyashikei", english: "Iyashikei" },
      { polish: "Rodzicielstwo", english: "Parenthood" },
    ],
  },
  {
    name: "Techniczne",
    tags: [
      { polish: "4-koma", english: "4-koma" },
      { polish: "Achromatyczny", english: "Achromatic" },
      { polish: "Reklama", english: "Advertisement" },
      { polish: "Antologia", english: "Anthology" },
      { polish: "CGI", english: "CGI" },
      { polish: "Epizodyczny", english: "Episodic" },
      { polish: "Flash", english: "Flash" },
      { polish: "Pełne CGI", english: "Full CGI" },
      { polish: "Pełny Kolor", english: "Full Color" },
      { polish: "Bez Dialogów", english: "No Dialogue" },
      { polish: "Non-fiction", english: "Non-fiction" },
      { polish: "POV", english: "POV" },
      { polish: "Lalkarstwo", english: "Puppetry" },
      { polish: "Rotoskopia", english: "Rotoscoping" },
      { polish: "Animacja Poklatkowa", english: "Stop Motion" },
    ],
  },
]

